In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [24]:
merged_all=pd.read_csv('/data/merge_all.csv', index_col='TransientID')
merged_all.head()

,Classification,Dec (J2000),SDSS,count,mag_info,mag_max,mag_mean,mag_median,mag_min,mag_std,magerr_max,magerr_mean,magerr_std,mjd_std,SN,baseline,mag_baseline
TransientID,,,,,,,,,,,,,,,,,
1210061091254108515,SN,8.91432,yes,196,18.31,21.3838,19.579940,19.67260,12.2208,0.826791,0.518022,0.246648,0.082713,944.440362,1,3056.797138,9.1630
1305091120654118444,SN,12.25101,yes,44,18.88,21.5437,20.017727,20.36435,12.4589,1.414599,0.630021,0.326672,0.126198,794.705168,1,2674.813849,9.0848
1007051071254133856,SN,8.00804,yes,9,19.08,21.3105,18.760311,19.05830,12.4652,2.544812,0.571777,0.248457,0.171531,436.012865,1,1379.137268,8.8453
1408311210014119351,Blazar,20.79720,yes,255,17.60,20.3146,18.769760,18.89440,11.6801,1.023209,0.620303,0.171679,0.051045,933.346573,0,2944.958031,8.6345
1502071150154145908,HPM,16.86533,no,13,12.52,20.8485,13.004977,12.35530,12.3152,2.356798,0.502200,0.085478,0.125210,783.335895,0,2840.216981,8.5333

In [25]:
merged_all.shape

(3861, 17)

In [26]:
merged_all.columns

Index(['Classification', 'Dec (J2000)', 'SDSS', 'count', 'mag_info', 'mag_max',
       'mag_mean', 'mag_median', 'mag_min', 'mag_std', 'magerr_max',
       'magerr_mean', 'magerr_std', 'mjd_std', 'SN', 'baseline',
       'mag_baseline'],
      dtype='str')

In [27]:
merged_all.dtypes

Classification        str
Dec (J2000)       float64
SDSS                  str
count               int64
mag_info          float64
mag_max           float64
mag_mean          float64
mag_median        float64
mag_min           float64
mag_std           float64
magerr_max        float64
magerr_mean       float64
magerr_std        float64
mjd_std           float64
SN                  int64
baseline          float64
mag_baseline      float64
dtype: object

In [28]:
merged_all.describe(include='all')

,Classification,Dec (J2000),SDSS,count,mag_info,mag_max,mag_mean,mag_median,mag_min,mag_std,magerr_max,magerr_mean,magerr_std,mjd_std,SN,baseline,mag_baseline
count,3861,3861.000000,3861,3861.000000,3861.000000,3861.000000,3861.000000,3861.000000,3861.000000,3734.000000,3861.000000,3861.000000,3.734000e+03,3734.000000,3861.000000,3861.000000,3861.000000
unique,31,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,SN,NaN,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1537,NaN,2934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,16.685183,NaN,103.246568,17.674556,19.995906,18.781613,18.788455,17.434965,0.654471,0.426169,0.221534,7.291601e-02,658.320518,0.398083,2069.962748,2.560941
std,NaN,20.018069,NaN,116.817806,1.778483,1.948634,1.750576,1.777806,1.903677,0.426848,0.191366,0.104186,4.729876e-02,330.053492,0.489566,1103.847270,1.564757
min,NaN,-28.110910,NaN,1.000000,12.010000,10.161000,10.161000,10.161000,10.161000,0.003536,0.050523,0.050041,5.837679e-08,0.004131,0.000000,0.000000,0.000000
25%,NaN,1.134370,NaN,12.000000,16.820000,19.578400,18.288712,18.247400,16.410400,0.404673,0.281947,0.142576,3.543235e-02,444.453770,0.000000,1182.854394,1.561200
50%,NaN,16.805390,NaN,45.000000,18.170000,20.817200,19.263350,19.273300,17.911800,0.579543,0.489833,0.215914,7.316918e-02,789.744669,0.000000,2633.957377,2.501800
75%,NaN,31.686380,NaN,171.000000,18.940000,21.231100,19.920520,19.955300,18.747000,0.834400,0.566324,0.290691,1.052722e-01,896.788671,1.000000,2951.977743,3.408100
max,NaN,69.945920,NaN,564.000000,20.720000,21.932800,21.538100,21.538100,21.538100,3.553848,1.306650,0.648143,3.674467e-01,2022.458161,1.000000,3130.294521,9.163000

In [29]:
merged_all.info()

<class 'pandas.DataFrame'>
Index: 3861 entries, 1210061091254108515 to 904031010684129833
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Classification  3861 non-null   str
 1   Dec (J2000)     3861 non-null   float64
 2   SDSS            3861 non-null   str
 3   count           3861 non-null   int64
 4   mag_info        3861 non-null   float64
 5   mag_max         3861 non-null   float64
 6   mag_mean        3861 non-null   float64
 7   mag_median      3861 non-null   float64
 8   mag_min         3861 non-null   float64
 9   mag_std         3734 non-null   float64
 10  magerr_max      3861 non-null   float64
 11  magerr_mean     3861 non-null   float64
 12  magerr_std      3734 non-null   float64
 13  mjd_std         3734 non-null   float64
 14  SN              3861 non-null   int64
 15  baseline        3861 non-null   float64
 16  mag_baseline    3861 non-null   float64
dtypes: float64(13), int64(2), str(2)
memory usage: 543.0 KB

In [30]:
print(merged_all['SDSS'].map(repr).unique())

<StringArray>
[''yes'', ''no'']
Length: 2, dtype: str

In [31]:
merged_all['SDSS'] = (
    merged_all['SDSS']
    .str.strip("'")
    .str.lower()
    .eq('yes')
    .astype(int)
)
print(merged_all['SDSS'].value_counts())

SDSS
1    2934
0     927
Name: count, dtype: int64

In [32]:
merged_all.head()

,Classification,Dec (J2000),SDSS,count,mag_info,mag_max,mag_mean,mag_median,mag_min,mag_std,magerr_max,magerr_mean,magerr_std,mjd_std,SN,baseline,mag_baseline
TransientID,,,,,,,,,,,,,,,,,
1210061091254108515,SN,8.91432,1,196,18.31,21.3838,19.579940,19.67260,12.2208,0.826791,0.518022,0.246648,0.082713,944.440362,1,3056.797138,9.1630
1305091120654118444,SN,12.25101,1,44,18.88,21.5437,20.017727,20.36435,12.4589,1.414599,0.630021,0.326672,0.126198,794.705168,1,2674.813849,9.0848
1007051071254133856,SN,8.00804,1,9,19.08,21.3105,18.760311,19.05830,12.4652,2.544812,0.571777,0.248457,0.171531,436.012865,1,1379.137268,8.8453
1408311210014119351,Blazar,20.79720,1,255,17.60,20.3146,18.769760,18.89440,11.6801,1.023209,0.620303,0.171679,0.051045,933.346573,0,2944.958031,8.6345
1502071150154145908,HPM,16.86533,0,13,12.52,20.8485,13.004977,12.35530,12.3152,2.356798,0.502200,0.085478,0.125210,783.335895,0,2840.216981,8.5333

In [33]:
merged_all=merged_all[merged_all['count']>1]
merged_all.info()

<class 'pandas.DataFrame'>
Index: 3734 entries, 1210061091254108515 to 1502201230664120626
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Classification  3734 non-null   str
 1   Dec (J2000)     3734 non-null   float64
 2   SDSS            3734 non-null   int64
 3   count           3734 non-null   int64
 4   mag_info        3734 non-null   float64
 5   mag_max         3734 non-null   float64
 6   mag_mean        3734 non-null   float64
 7   mag_median      3734 non-null   float64
 8   mag_min         3734 non-null   float64
 9   mag_std         3734 non-null   float64
 10  magerr_max      3734 non-null   float64
 11  magerr_mean     3734 non-null   float64
 12  magerr_std      3734 non-null   float64
 13  mjd_std         3734 non-null   float64
 14  SN              3734 non-null   int64
 15  baseline        3734 non-null   float64
 16  mag_baseline    3734 non-null   float64
dtypes: float64(13), int64(3), str(1)
memory usage: 525.1 KB

In [34]:
merged_all.describe(include='all')

,Classification,Dec (J2000),SDSS,count,mag_info,mag_max,mag_mean,mag_median,mag_min,mag_std,magerr_max,magerr_mean,magerr_std,mjd_std,SN,baseline,mag_baseline
count,3734,3734.000000,3734.000000,3734.000000,3734.000000,3734.000000,3734.000000,3734.000000,3734.000000,3734.000000,3734.000000,3734.000000,3.734000e+03,3734.000000,3734.000000,3734.000000,3734.000000
unique,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,SN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,16.575655,0.758168,106.724156,17.663626,20.011222,18.755628,18.762704,17.363179,0.654471,0.429844,0.218249,7.291601e-02,658.320518,0.388056,2140.365873,2.648043
std,NaN,20.012678,0.428250,117.230111,1.784417,1.950651,1.741854,1.770246,1.864507,0.426848,0.191596,0.100742,4.729876e-02,330.053492,0.487373,1053.187411,1.516922
min,NaN,-28.110910,0.000000,2.000000,12.010000,12.021700,11.335528,11.238100,10.357700,0.003536,0.050523,0.050041,5.837679e-08,0.004131,0.000000,0.006189,0.005000
25%,NaN,1.047273,1.000000,14.000000,16.790000,19.607025,18.268205,18.226750,16.358700,0.404673,0.287538,0.141833,3.543235e-02,444.453770,0.000000,1473.863530,1.700050
50%,NaN,16.642115,1.000000,50.000000,18.150000,20.851200,19.248788,19.250950,17.862200,0.579543,0.495077,0.214075,7.316918e-02,789.744669,0.000000,2658.258885,2.539100
75%,NaN,31.550113,1.000000,176.750000,18.940000,21.237650,19.892404,19.929050,18.688450,0.834400,0.567750,0.287167,1.052722e-01,896.788671,1.000000,2953.988803,3.445175
max,NaN,69.945920,1.000000,564.000000,20.720000,21.932800,21.333600,21.424900,21.220000,3.553848,1.306650,0.569796,3.674467e-01,2022.458161,1.000000,3130.294521,9.163000

In [35]:
y=merged_all['SN']
X=merged_all.drop(columns=['Classification','SN'])

In [36]:
X.shape

(3734, 15)

In [37]:
y.shape

(3734,)

In [38]:
X.columns

Index(['Dec (J2000)', 'SDSS', 'count', 'mag_info', 'mag_max', 'mag_mean',
       'mag_median', 'mag_min', 'mag_std', 'magerr_max', 'magerr_mean',
       'magerr_std', 'mjd_std', 'baseline', 'mag_baseline'],
      dtype='str')

In [39]:
y.value_counts()

SN
0    2285
1    1449
Name: count, dtype: int64

In [40]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,stratify=y)

In [41]:
X_train.shape

(2987, 15)

In [42]:
X_test.shape

(747, 15)

In [43]:
y_test.value_counts()

SN
0    457
1    290
Name: count, dtype: int64

In [44]:
y_train.value_counts()

SN
0    1828
1    1159
Name: count, dtype: int64

In [46]:
X_test.to_csv('C:\\Users\\dawit\\PycharmProjects\\supernova\\data\\X_test.csv',index=False)
X_train.to_csv('C:\\Users\\dawit\\PycharmProjects\\supernova\\data\\X_train.csv',index=False)
y_train.to_csv('C:\\Users\\dawit\\PycharmProjects\\supernova\\data\\y_train.csv',index=False)
y_test.to_csv('C:\\Users\\dawit\\PycharmProjects\\supernova\\data\\y_test.csv',index=False)